# Generated by Django 5.1.1 on 2024-10-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("chat_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(max_length=16)),
                ("content", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
